name: CI for Better Data Component Tooltip

on:
  push:
    paths:
      - .github/workflows/**
      - src/**
      - '*.gradle'
  pull_request:
    paths:
      - .github/workflows/**
      - src/**
      - '*.gradle'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Copy Guide Book
        run: ./gradlew copyGuidebook

      - name: Build with Gradle
        run: ./gradlew build

      - name: Read Properties
        id: 'properties'
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'mod_id mod_name'

      - name: Get Version
        id: var
        run: |
          MESSAGE=$(ls build/libs/* | grep sources.jar -v | grep shadow.jar -v | grep slim.jar -v | awk -F '${{ steps.properties.outputs.mod_id }}-|.jar' '{print $2}')
          echo version=$MESSAGE >> $GITHUB_OUTPUT

      - name: Get Commit Short hash
        id: hash
        run: echo "short_hash=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: "${{ steps.properties.outputs.mod_name }} v${{ steps.var.outputs.version }}-${{ env.short_hash }}"
          path: build/libs/*.jar
